import "./globals.css";
import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { Providers } from "../provider";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "user app",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body suppressHydrationWarning className={inter.className}>{children}</body>
      </Providers>
    </html>
  );
}
